export interface FlatFoxResult {
    "pk": number,
    "slug": string,
    "url": string,
    "short_url": string,
    "thread_url": any,
    "submit_url": string,
    "status": string,
    "created": string,
    "offer_type": "RENT" | string,
    "object_category": "APARTMENT" | string,
    "object_type": "APARTMENT" | string,
    "reference": string,
    "ref_property": string,
    "ref_house": string,
    "ref_object": string,
    "price_display": number,
    "price_display_type": "TOTAL" | string,
    "price_unit": "monthly" | string,
    "published": string,
    "rent_net": number,
    "rent_charges": number,
    "rent_gross": number,
    "short_title": string,
    "public_title": string,
    "pitch_title": string,
    "description_title": string,
    "description": string,
    "surface_living": number,
    "surface_property": number,
    "surface_usable": number,
    "surface_usable_minimum": number,
    "volume": number,
    "space_display": number,
    "number_of_rooms": string,
    "floor": number,
    "attributes": {
        "name": string
    }[]
    "is_furnished": boolean,
    "is_temporary": boolean,
    "is_selling_furniture": boolean,
    "show_exact_address": boolean,
    "street": string,
    "zipcode": number,
    "city": string,
    "public_address": string,
    "latitude": string,
    "longitude": string,
    "year_built": string,
    "year_renovated": string,
    "moving_date_type": "dat" | string,
    "moving_date": string,
    "video_url": string,
    "tour_url": string,
    "website_url": string,
    "live_viewing_url": string,
    "cover_image": FlatFoxFlatImage,
    "images": FlatFoxFlatImage[]
    "documents": any[],
    "agency": {
        "name": string,
        "name_2": string,
        "street": string,
        "zipcode": string,
        "city": string,
        "country": string,
        "logo": string
    },
    "reserved": boolean,
    "full_address": string,
    "formatted": {
        "short_title": string,
        "rent_net": string,
        "rent_gross": string,
        "rent_charges": string,
        "price_unit": string,
        "space": string,
        "floor": string,
        "number_of_rooms": string,
        "available": string,
        "livingspace": string
    },
    "rent_title": string,
    "livingspace": string,
    "organization": any,
    "cover_image_url": string,
    "title": string,
    "rent_display": number,
    "category": "APARTMENT" | string,
    "public_subtitle": string
}

export type FlatFoxFlatImage = {
    "pk": number,
    "caption": string,
    "url": string,
    "url_thumb_m": string,
    "url_listing_search": string,
    "search_url": string,
    "ordering": number,
    "width": number,
    "height": number
}